# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-27 19:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0002_auto_20180607_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_sku', models.CharField(max_length=50, verbose_name='系统SKU')),
                ('img', models.ImageField(blank=True, default='image/default2.jpg', null=True, upload_to='image/%Y/%m')),
                ('order_number', models.CharField(max_length=10, verbose_name='工单号')),
                ('status', models.CharField(choices=[('0', '订单已退回'), ('1', '新建-保存'), ('2', '提交-等待审批'), ('3', '已审批-等待采购'), ('4', '已采购-等待确认'), ('5', '订单已完成')], default='0', max_length=10, verbose_name='订单状态')),
                ('product_chinese_name', models.CharField(max_length=500, verbose_name='产品中文名')),
                ('comparison_code', models.CharField(max_length=20, verbose_name='对照码')),
                ('finish_status', models.CharField(choices=[('0', '成品'), ('1', '配件')], default='0', max_length=10, verbose_name='是否成品')),
                ('purchase_link', models.CharField(max_length=500, verbose_name='采购链接')),
                ('remaining_stock_quantity', models.IntegerField(verbose_name='剩余库存数量')),
                ('issued_quantity', models.IntegerField(verbose_name='已发出数量')),
                ('sales_30', models.CharField(max_length=50, verbose_name='最近30天销量')),
                ('order_quantity', models.IntegerField(verbose_name='下单数量')),
                ('purchase_quantity', models.IntegerField(verbose_name='还需采购数量')),
                ('add_time', models.DateField(default=datetime.datetime.today, verbose_name='创建时间')),
                ('remark', models.CharField(max_length=500, verbose_name='备注')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation', to=settings.AUTH_USER_MODEL, verbose_name='运营')),
                ('operation_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_manager', to=settings.AUTH_USER_MODEL, verbose_name='运营经理')),
                ('purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaser', to=settings.AUTH_USER_MODEL, verbose_name='采购人员')),
                ('warehouse_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_staff', to=settings.AUTH_USER_MODEL, verbose_name='仓储人员')),
            ],
        ),
    ]
