# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-01 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20200328_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_sku', models.CharField(max_length=50, verbose_name='系统SKU')),
                ('stock_quantity', models.IntegerField(verbose_name='库存数量')),
                ('finish_status', models.CharField(choices=[('0', '成品'), ('1', '配件')], default='0', max_length=10, verbose_name='是否成品')),
                ('accessories_name', models.CharField(max_length=50, verbose_name='配件名称')),
                ('position', models.CharField(max_length=500, verbose_name='位置')),
                ('remark', models.CharField(max_length=500, verbose_name='备注')),
                ('add_time', models.DateField(default=datetime.datetime.today, verbose_name='添加时间')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='issued_quantity',
            field=models.IntegerField(null=True, verbose_name='已发出数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_quantity',
            field=models.IntegerField(null=True, verbose_name='还需采购数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_stock_quantity',
            field=models.IntegerField(null=True, verbose_name='剩余库存数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_30',
            field=models.CharField(max_length=50, null=True, verbose_name='最近30天销量'),
        ),
    ]
