# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-03 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20200401_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(null=True, verbose_name='下单数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_quantity',
            field=models.IntegerField(null=True, verbose_name='采购数量'),
        ),
    ]
