# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20200403_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remark1',
            field=models.CharField(max_length=500, null=True, verbose_name='运营经理备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='remark2',
            field=models.CharField(max_length=500, null=True, verbose_name='采购备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='remark3',
            field=models.CharField(max_length=500, null=True, verbose_name='仓库备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(max_length=500, null=True, verbose_name='运营备注'),
        ),
    ]
