# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20200403_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change_time',
            field=models.DateField(auto_now=True, verbose_name='最后一次修改时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='accessories_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='配件名称'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='position',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='备注'),
        ),
    ]
