# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-15 11:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0008_auto_20200407_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternalSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='系统SKU')),
                ('add_time', models.DateField(default=datetime.datetime.today, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='系统SKU')),
                ('order_quantity', models.IntegerField(null=True, verbose_name='下单数量')),
                ('status', models.CharField(choices=[('0', '订单已退回'), ('1', '新建-保存'), ('2', '提交-等待审批'), ('3', '已审批-订单完成')], default='0', max_length=10, verbose_name='订单状态')),
                ('add_time', models.DateField(default=datetime.datetime.today, verbose_name='添加时间')),
                ('maternal_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_order_maternal_sku', to='personal.MaternalSku', verbose_name='母体SKU')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_order_operation', to=settings.AUTH_USER_MODEL, verbose_name='运营')),
                ('operation_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_order_operation_manager', to=settings.AUTH_USER_MODEL, verbose_name='运营经理')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='采购状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.ImageField(blank=True, default='image/default2.png', null=True, upload_to='image/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='order',
            name='issued_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='已发出数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_manager', to=settings.AUTH_USER_MODEL, verbose_name='运营经理'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='下单数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_stock_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='剩余库存数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='运营备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='运营经理备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='采购备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='仓库备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='maternal_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maternal_sku', to='personal.MaternalSku', verbose_name='母体SKU'),
        ),
        migrations.AddField(
            model_name='stock',
            name='maternal_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_maternal_sku', to='personal.MaternalSku', verbose_name='母体SKU'),
        ),
    ]
